### ISSUE TITLE
Prisma adapter from Mostafatalaat770

### ISSUE THREAD

**Issue by pi0neerpat** [SeanCassiere/oidc-provider-server-example#4]
Doing some research on this and saw someone recently contributed a prisma adapter. Maybe its helpful! https://github.com/panva/node-oidc-provider/blob/main/example/adapters/contributed/prisma.ts

**Comment by pi0neerpat** [comment]
I also started working on my own adaptation of theirs here https://github.com/UseKeyp/oauth2-server-redwood/pull/2

**Comment by SeanCassiere** [comment]
Thanks!

Honestly, I'd taken a break from this since life got a bit busy, but I'll look at getting this done in the next few months.
